# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            '#DeafBiz'
tagline:          'Support Deaf Today!'
description:      'A curating of Deaf-Owned Businesses #trubiz. Not guaranteed to be perfect. Made by <a href="https://twitter.com/kratsg" target="_blank">@kratsg</a>.'
url:              https://kratsg.github.io/deaf-owned-businesses/
baseurl:          /deaf-owned-businesses/

author:
  name:           'Giordon Stark'
  url:            https://twitter.com/kratsg

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/kratsg/deaf-owned-businesses

plugins_dir:
  - jekyll-paginate
  - jekyll-gist
